const Data = {
  products: [
    {
      image: "/images/motorcycle.png",
      name: "Motorcycle",
      brand: "Riders",
      price: 455,
      ratings: 4.5,
      reviews: 6,
      category: "motorcycles",
    },
    {
      image: "/images/ford.png",
      name: "Ford",
      brand: "Ford",
      price: 655,
      ratings: 3.5,
      reviews: 6,
      category: "cars",
    },
    {
      image: "/images/motorcycle2.png",
      name: "Cherry Wheel",
      brand: "Motorcycle",
      price: 355,
      ratings: 3.5,
      reviews: 6,
      category: "motorcycles",
    },
    {
      image: "/images/fordBig.png",
      name: "Ford",
      brand: "Ford",
      price: 685,
      ratings: 3.5,
      reviews: 6,
      category: "Cars",
    },
    {
      image: "/images/fordOpen.png",
      name: "Lorry Ford",
      brand: "Ford",
      price: 655,
      ratings: 3.5,
      reviews: 6,
      category: "Cars",
    },
    {
      image: "/images/tractors.png",
      name: "Tractor",
      brand: "Tractor",
      price: 955,
      ratings: 3.5,
      reviews: 6,
      category: "tractors",
    },
    {
      image: "/images/tractorGo.png",
      name: "Tractor",
      brand: "Tractor",
      price: 985,
      ratings: 3.5,
      reviews: 6,
      category: "tractors",
    },
    {
      image: "/images/sports.png",
      name: "Sports Bike",
      brand: "Race Bike",
      price: 575,
      ratings: 3.5,
      reviews: 6,
      category: "sports",
    },
    {
      image: "/images/sports2.png",
      name: "Sports Bike",
      brand: "Race Speedy",
      price: 465,
      ratings: 3.5,
      reviews: 6,
      category: "sports",
    },
  ],
};
export default Data;
